### ISSUE TITLE
[Request] Add a simple makefile + make it installable with `go install`

### ISSUE THREAD

**Issue by xplshn** [Krzysztofz01/pixel-sorter#53]
:)

Thanks! Awesome project!

**Comment by Krzysztofz01** [comment]
Hello!

Thanks a lot for your interest in the project. At the moment, the project is developed as a library and CLI tool being a “testbed” for a larger tool using “pixel-sorter”.

For this reason, the program for now does not support `go install` and this is unlikely to change until the first full release. As far as the **Makefile** script is concerned, it is not expected to be added at this point, because the build system is **Taskfile**, which integrates better with those using Go as a programming language and also integrates better with other tools used.

**Comment by xplshn** [comment]
Taskfile is a hassle to use if you aren't familiar with it, makefiles are very simple to use. Anyways, thanks for clarifying everything.

**Comment by Krzysztofz01** [comment]
The issue will be reconsidered after the first stable release.
